[phases.setup]
nixPkgs = ["nodejs_20", "pnpm", "libreoffice-still"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build", "node scripts/migrate-production.mjs"]

[start]
cmd = "pnpm start"
