import { useState, useEffect, useRef } from "react";
import { trpc } from "@/lib/trpc";
import { useTimezone } from "@/hooks/useTimezone";
import { toast } from "sonner";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Mail,
  Search,
  Filter,
  Download,
  Clock,
  CheckCircle2,
  AlertCircle,
  Calendar,
  Briefcase,
  TrendingUp,
  Zap,
  Info,
  Bell,
  RefreshCw,
  MailCheck,
  Eye,
} from "lucide-react";
import * as XLSX from "xlsx";

type NotificationType =
  | "milestone_due_soon"
  | "milestone_overdue"
  | "project_completed"
  | "project_assigned"
  | "project_updated"
  | "milestone_reminder"
  | "delay"
  | "ai_alert"
  | "general";

export default function NotificationHistory() {
  const { formatDateTime: tzFormatDateTime } = useTimezone();
  const [searchTerm, setSearchTerm] = useState("");
  const [filterType, setFilterType] = useState<NotificationType | "all">("all");
  const [filterRead, setFilterRead] = useState<"all" | "read" | "unread">(
    "all"
  );
  const hasAutoGenerated = useRef(false);

  const meQuery = trpc.auth.me.useQuery(undefined, {
    retry: false,
    refetchOnWindowFocus: false,
  });
  const user = meQuery.data ?? null;

  // Obtener todas las notificaciones
  const { data: notifications, isLoading, refetch } =
    trpc.notifications.getUserNotifications.useQuery({
      limit: 1000,
      unreadOnly: false,
    });

  // Generar notificaciones automáticas
  const generateNotifications =
    trpc.notifications.checkAndCreateAutoNotifications.useMutation({
      onSuccess: (data) => {
        const totalCreated = (data.upcomingCount || 0) + (data.overdueCount || 0);
        if (totalCreated > 0) {
          toast.success(`${totalCreated} nueva(s) notificación(es) generada(s)`);
        }
        refetch();
      },
      onError: (error) => {
        console.warn("[Notificaciones] Error auto-generando:", error.message);
      },
    });

  // Marcar como leída
  const markAsRead = trpc.notifications.markAsRead.useMutation({
    onSuccess: () => {
      refetch();
    },
  });

  // Marcar todas como leídas
  const markAllAsRead = trpc.notifications.markAllAsRead.useMutation({
    onSuccess: () => {
      toast.success("Todas las notificaciones marcadas como leídas");
      refetch();
    },
  });

  // Enviar email de recordatorio
  const sendEmailReminder = trpc.notifications.sendEmailReminder.useMutation({
    onSuccess: (data) => {
      if (data.success) {
        toast.success("Email de recordatorio enviado correctamente");
      } else {
        toast.error("No se pudo enviar el email. Verifica la configuración de email.");
      }
    },
    onError: (error) => {
      toast.error(error.message);
    },
  });

  // Auto-generar notificaciones al cargar la página (una sola vez)
  useEffect(() => {
    if (!hasAutoGenerated.current && user) {
      hasAutoGenerated.current = true;
      generateNotifications.mutate();
    }
  }, [user]);

  // Filtrar notificaciones
  const filteredNotifications =
    notifications?.filter((notif) => {
      const matchesSearch =
        notif.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
        notif.message.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesType = filterType === "all" || notif.type === filterType;
      const matchesRead =
        filterRead === "all" ||
        (filterRead === "read" && notif.isRead) ||
        (filterRead === "unread" && !notif.isRead);

      return matchesSearch && matchesType && matchesRead;
    }) || [];

  const unreadCount = notifications?.filter((n) => !n.isRead).length || 0;

  // Exportar a Excel
  const handleExport = () => {
    const data = filteredNotifications.map((notif) => ({
      Fecha: tzFormatDateTime(notif.sentAt),
      Tipo: getTypeLabel(notif.type),
      Título: notif.title,
      Mensaje: notif.message,
      Leída: notif.isRead ? "Sí" : "No",
      "Proyecto ID": notif.projectId || "-",
    }));

    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Notificaciones");
    XLSX.writeFile(
      wb,
      `notificaciones_${new Date().toISOString().split("T")[0]}.xlsx`
    );
  };

  const getTypeIcon = (type: NotificationType) => {
    switch (type) {
      case "milestone_due_soon":
        return <Clock className="h-4 w-4" />;
      case "milestone_overdue":
        return <AlertCircle className="h-4 w-4" />;
      case "project_completed":
        return <CheckCircle2 className="h-4 w-4" />;
      case "project_assigned":
        return <Briefcase className="h-4 w-4" />;
      case "project_updated":
        return <TrendingUp className="h-4 w-4" />;
      case "milestone_reminder":
        return <Bell className="h-4 w-4" />;
      case "delay":
        return <AlertCircle className="h-4 w-4" />;
      case "ai_alert":
        return <Zap className="h-4 w-4" />;
      case "general":
        return <Info className="h-4 w-4" />;
      default:
        return <Mail className="h-4 w-4" />;
    }
  };

  const getTypeLabel = (type: NotificationType) => {
    switch (type) {
      case "milestone_due_soon":
        return "Hito Próximo";
      case "milestone_overdue":
        return "Hito Vencido";
      case "project_completed":
        return "Proyecto Completado";
      case "project_assigned":
        return "Proyecto Asignado";
      case "project_updated":
        return "Proyecto Actualizado";
      case "milestone_reminder":
        return "Recordatorio";
      case "delay":
        return "Retraso";
      case "ai_alert":
        return "Alerta IA";
      case "general":
        return "General";
      default:
        return type;
    }
  };

  const getTypeBadgeColor = (type: NotificationType) => {
    switch (type) {
      case "milestone_due_soon":
        return "bg-yellow-100 text-yellow-700";
      case "milestone_overdue":
        return "bg-red-100 text-red-700";
      case "project_completed":
        return "bg-green-100 text-green-700";
      case "project_assigned":
        return "bg-blue-100 text-blue-700";
      case "project_updated":
        return "bg-purple-100 text-purple-700";
      case "milestone_reminder":
        return "bg-orange-100 text-orange-700";
      case "delay":
        return "bg-red-100 text-red-700";
      case "ai_alert":
        return "bg-indigo-100 text-indigo-700";
      case "general":
        return "bg-gray-100 text-gray-700";
      default:
        return "bg-gray-100 text-gray-700";
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50 p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <h1 className="text-xl sm:text-2xl lg:text-3xl font-bold text-gray-900 flex items-center gap-3">
              <Mail className="h-8 w-8 text-orange-500" />
              Notificaciones
            </h1>
            <p className="text-gray-600 mt-1">
              Gestiona tus notificaciones y alertas del sistema
            </p>
          </div>
          <div className="flex gap-2 flex-wrap">
            <Button
              onClick={() => {
                hasAutoGenerated.current = false;
                generateNotifications.mutate();
              }}
              variant="outline"
              className="border-orange-300 text-orange-700 hover:bg-orange-50"
              disabled={generateNotifications.isPending}
            >
              <RefreshCw className={`h-4 w-4 mr-2 ${generateNotifications.isPending ? 'animate-spin' : ''}`} />
              {generateNotifications.isPending ? "Actualizando..." : "Actualizar"}
            </Button>
            {unreadCount > 0 && (
              <Button
                onClick={() => markAllAsRead.mutate()}
                variant="outline"
                className="border-blue-300 text-blue-700 hover:bg-blue-50"
                disabled={markAllAsRead.isPending}
              >
                <Eye className="h-4 w-4 mr-2" />
                Marcar todas como leídas
              </Button>
            )}
            <Button
              onClick={handleExport}
              className="bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600"
              disabled={filteredNotifications.length === 0}
            >
              <Download className="h-4 w-4 mr-2" />
              Exportar
            </Button>
          </div>
        </div>

        {/* Estadísticas */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card className="shadow-apple border-0">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-600">Total</p>
                  <p className="text-2xl font-bold text-gray-900">
                    {notifications?.length || 0}
                  </p>
                </div>
                <Mail className="h-8 w-8 text-orange-500" />
              </div>
            </CardContent>
          </Card>

          <Card className="shadow-apple border-0">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-600">No Leídas</p>
                  <p className="text-2xl font-bold text-red-600">
                    {unreadCount}
                  </p>
                </div>
                <AlertCircle className="h-8 w-8 text-red-500" />
              </div>
            </CardContent>
          </Card>

          <Card className="shadow-apple border-0">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-600">Hitos Vencidos</p>
                  <p className="text-2xl font-bold text-amber-600">
                    {notifications?.filter((n) => n.type === "milestone_overdue").length || 0}
                  </p>
                </div>
                <Clock className="h-8 w-8 text-amber-500" />
              </div>
            </CardContent>
          </Card>

          <Card className="shadow-apple border-0">
            <CardContent className="pt-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm text-gray-600">Filtradas</p>
                  <p className="text-2xl font-bold text-blue-600">
                    {filteredNotifications.length}
                  </p>
                </div>
                <Filter className="h-8 w-8 text-blue-500" />
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Filtros */}
        <Card className="shadow-apple border-0">
          <CardContent className="pt-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Búsqueda */}
              <div className="relative">
                <Search className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                <Input
                  placeholder="Buscar en notificaciones..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-10"
                />
              </div>

              {/* Filtro por tipo */}
              <Select
                value={filterType}
                onValueChange={(value) =>
                  setFilterType(value as typeof filterType)
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Tipo de notificación" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">Todos los tipos</SelectItem>
                  <SelectItem value="milestone_due_soon">
                    Hito Próximo
                  </SelectItem>
                  <SelectItem value="milestone_overdue">
                    Hito Vencido
                  </SelectItem>
                  <SelectItem value="project_completed">
                    Proyecto Completado
                  </SelectItem>
                  <SelectItem value="project_assigned">
                    Proyecto Asignado
                  </SelectItem>
                  <SelectItem value="project_updated">
                    Proyecto Actualizado
                  </SelectItem>
                  <SelectItem value="milestone_reminder">
                    Recordatorio
                  </SelectItem>
                  <SelectItem value="delay">Retraso</SelectItem>
                  <SelectItem value="ai_alert">Alerta IA</SelectItem>
                  <SelectItem value="general">General</SelectItem>
                </SelectContent>
              </Select>

              {/* Filtro por estado de lectura */}
              <Select
                value={filterRead}
                onValueChange={(value) =>
                  setFilterRead(value as typeof filterRead)
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Estado" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">Todas</SelectItem>
                  <SelectItem value="unread">No leídas</SelectItem>
                  <SelectItem value="read">Leídas</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardContent>
        </Card>

        {/* Lista de notificaciones */}
        <Card className="shadow-apple border-0">
          <CardHeader>
            <CardTitle>
              Notificaciones ({filteredNotifications.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="space-y-4">
                {[1, 2, 3, 4, 5].map((i) => (
                  <Skeleton key={i} className="h-20 w-full" />
                ))}
              </div>
            ) : filteredNotifications.length === 0 ? (
              <div className="text-center py-12">
                <Mail className="h-12 w-12 text-gray-300 mx-auto mb-4" />
                <p className="text-gray-500 text-lg font-medium">
                  No se encontraron notificaciones
                </p>
                <p className="text-gray-400 text-sm mt-1">
                  Las notificaciones se generan automáticamente cuando hay hitos próximos a vencer o vencidos
                </p>
                <Button
                  onClick={() => generateNotifications.mutate()}
                  variant="outline"
                  className="mt-4"
                  disabled={generateNotifications.isPending}
                >
                  <RefreshCw className={`h-4 w-4 mr-2 ${generateNotifications.isPending ? 'animate-spin' : ''}`} />
                  Verificar ahora
                </Button>
              </div>
            ) : (
              <div className="space-y-3">
                {filteredNotifications.map((notif) => (
                  <div
                    key={notif.id}
                    className={`p-4 rounded-lg border transition-all hover:shadow-md cursor-pointer ${
                      notif.isRead
                        ? "bg-white border-gray-200"
                        : "bg-orange-50 border-orange-200"
                    }`}
                    onClick={() => {
                      if (!notif.isRead) {
                        markAsRead.mutate({ id: notif.id });
                      }
                    }}
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex items-start gap-3 flex-1">
                        <div
                          className={`p-2 rounded-lg shrink-0 ${getTypeBadgeColor(
                            notif.type
                          )}`}
                        >
                          {getTypeIcon(notif.type)}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1 flex-wrap">
                            <h3 className="font-semibold text-gray-900">
                              {notif.title}
                            </h3>
                            {!notif.isRead && (
                              <Badge className="bg-red-500 text-white text-xs">
                                Nuevo
                              </Badge>
                            )}
                          </div>
                          <p className="text-sm text-gray-600 mb-2">
                            {notif.message}
                          </p>
                          <div className="flex items-center gap-4 text-xs text-gray-500 flex-wrap">
                            <span className="flex items-center gap-1">
                              <Calendar className="h-3 w-3" />
                              {tzFormatDateTime(notif.sentAt)}
                            </span>
                            <Badge
                              variant="outline"
                              className={getTypeBadgeColor(notif.type)}
                            >
                              {getTypeLabel(notif.type)}
                            </Badge>
                            {notif.projectId && (
                              <a
                                href={`/projects/${notif.projectId}`}
                                className="text-orange-600 hover:text-orange-800 underline flex items-center gap-1"
                                onClick={(e) => e.stopPropagation()}
                              >
                                Ver proyecto →
                              </a>
                            )}
                          </div>
                        </div>
                      </div>
                      <div className="flex gap-1 shrink-0">
                        {(notif.type === "milestone_due_soon" || notif.type === "milestone_overdue") && notif.projectId && (
                          <Button
                            size="sm"
                            variant="outline"
                            className="text-xs border-orange-300 text-orange-700 hover:bg-orange-50"
                            onClick={(e) => {
                              e.stopPropagation();
                              sendEmailReminder.mutate({
                                notificationId: notif.id,
                              });
                            }}
                            disabled={sendEmailReminder.isPending}
                            title="Enviar recordatorio por email"
                          >
                            <MailCheck className="h-3 w-3 mr-1" />
                            Email
                          </Button>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
